<?php
/**
* Database index PHTML file
*
*   
* LICENSE: Commercial
* 
* @package Application
* @copyright Ivan Dudas
* @license http://www.example.com/license
* @version  1.0.0
* @link  http://www.example.com
* @since 2013
* @see ErrorController::errorcontrollAction()
*/

?>

<h3>Some random person list</h3>

<table border="1">
<tr>
<th>Num.</th>
<th>Name</th>
<th>Phone</th>
<th>Date</th>
</tr>
<?php 
$persons = $this->persons;

foreach ($persons as $key => $person) {
    echo "<tr>";
        echo "<td>$key</td>";
        echo "<td>$person->name</td>";
        echo "<td>$person->phone</td>";
        echo "<td>$person->date</td>";
    echo "</tr>";
}
?>
</table>