<?php

$db = $this->db;

?>


<div class="container" style="margin-top: 60px;">
    
   <p class="lead text-center">Hello World from GLDemo!</p>
   
   <table class="table table-bordered">
       
       <caption>This is a placeholder for table.</caption>
       
        <thead>
          <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Date</th>            
          </tr>
        </thead>
        <tbody>
           
            
        </tbody>
       
        
   </table>
    
</div>
