<?php

$nesto = $this->nesto;

?>


<div class="container" style="margin-top: 60px;">
    
   <p class="lead text-center">Hello World</p>
   
   <table class="table table-bordered">
       
       <caption>Ultimate table of everything</caption>
       
        <thead>
          <tr>
            <th>First Name</th>
            <th>Surname</th>
            <th>Car</th>
            <th>Computer</th>
          </tr>
        </thead>
       
        <tbody>
            <tr class="success">
                <td>Bill</td>
                <td>Gates</td>
                <td>Ferrari</td>
                <td>Windows phone</td>
            </tr>
        </tbody>
   </table>
   
    <button class="btn btn-large btn-primary" type="button">I don't actually do anything, i am just here for the violence</button>
    <?php echo $nesto;?>
</div>

