<?php
/**
* Database index PHTML file
*
*   
* LICENSE: Commercial
* 
* @package Application
* @copyright Ivan Dudas
* @license http://www.example.com/license
* @version  1.0.0
* @link  http://www.example.com
* @since 2013
* @see ErrorController::errorcontrollAction()
*/

$persons = $this->persons;

?>

<div class="container" style="margin-top: 60px;">
    
    <div class="page-header">
        <h1>GL demo<small> Database insert example</small></h1>
    </div> 
   
   <table class="table table-bordered">
       
       <caption>This is a placeholder for table.</caption>
       
        <thead>
          <tr>
            <th>Num.</th>
            <th>Name</th>
            <th>Phone</th>
            <th>Date</th>            
          </tr>
        </thead>
        <tbody>
            
            <?php
            
            foreach ($persons as $key=>$onePerson) {
                echo '<tr>';
                echo '<td class="span2">'.$key.'</td>';
                echo '<td class="span4">'.$onePerson->name.'</td>';
                echo '<td class="span4">'.$onePerson->phone.'</td>';
                echo '<td class="span2">'.$onePerson->date.'</td>';
                echo '</tr>';
            }
            
            ?>
            
        </tbody>
       
        
   </table>
    
</div>