<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>GL Hello World</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">      
  <link href="<?php echo APP_URL;  ?>bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">          
  <script src="http://code.jquery.com/jquery.js"></script>
  <script src="<?php echo APP_URL;  ?>bootstrap/js/bootstrap.min.js"></script>
  
</head>
<body>
    
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
      <div class="wrapper" style="width: 900px; margin-left: auto; margin-right: auto;">
          <p class="brand text-center">This is useful information about GitLaunchpad.</p>          
      </div>
  </div>
</div>
 
<?php  echo $this->layout()->content ?>
 
</body>
</html>
